---
server.port: 8082

spring:

  application:
    name: atm

  config:
    import: 'optional:configserver:'

  flyway:
    baseline-on-migrate: true
    enabled: true 
    locations: classpath:db/migration/{vendor}
    out-of-order: false
    table: atm-schema-version
    validate-on-migrate: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    
  r2dbc: 
    url: r2dbc:h2:mem:///testdb    
    username: sa
    
eureka:
  client:
    enabled: false
    
---

spring:
  config.activate.on-profile: mysql
 
  r2dbc: 
    properties.sslMode: TRUST  
    properties.tlsVersion: TLSv1.2   
    properties.allowPublicKeyRetrieval: true    
    
---

spring:
  config.activate.on-profile: eureka
  
eureka:
 client:
   enabled: true