apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: atm
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: atm
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  env:
  - name: MANAGEMENT_HEALTH_PROBES_ENABLED
    value: "true"
  - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
    value: "true"
  - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
    value: always
  - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
    value: /actuator
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: '*'
  - name: MANAGEMENT_SERVER_PORT
    value: "8081"
  - name: SERVER_PORT
    value: "8080"
  - name: ORG_SPRINGFRAMEWORK_CLOUD_BINDINGS_BOOT_ENABLE
    value: "true"
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_MAVEN_ACTIVE_PROFILES
        value: native
      - name: BP_NATIVE_IMAGE
        value: "true"
      - name: MANAGEMENT_HEALTH_PROBES_ENABLED
        value: "true"
      - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
        value: "true"
      - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always
      - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
        value: /actuator
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: '*'
      - name: MANAGEMENT_SERVER_PORT
        value: "8081"
      - name: SERVER_PORT
        value: "8080"    
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"             
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  source:
    git:
      url: https://gitlab.eng.vmware.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: atm-locator
