apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: atm-locator-angular
spec:
  build:
    nonSecretEnv:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: dist
    buildpacks: {}
    path: ../..
  ports:
  - name: main
    port: 8080
