apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: branch
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: branch
spec:
  env:
  - name: spring_profiles_active
    value: eureka
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"
  serviceClaims:
  - name: registry
    ref:
      apiVersion: service-registry.spring.apps.tanzu.vmware.com/v1alpha1
      kind: EurekaServer
      name: registry-atm-locator
  source:
    git:
      url: https://gitlab.eng.vmware.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: branch
 