---
# ####################################################
# application.yaml
#
# Provides default settings, along with configuration for optional features
# which can be activated using Spring Boot profiles.
#
# Available profiles:
# - prometheus            exposure of metrics in Prometheus endpoint
# - redis                 storage of session and rate limiting data in Redis
# - response-cache-local  HTTP request caching
# - sso                   OIDC configuration
# - tls-server            TLS server termination configuration
# - wavefront             publication of metrics and tracing information to Wavefront
# - zipkin                publication of tracing information to Zipkin
#
# Activating the prometheus or wavefront profiles will turn on metrics features
# Activating the wavefront or zipkin profiles will turn on tracing features
# ####################################################
management:
  wavefront:
    metrics:
      export:
        enabled: false
  endpoint:
    gateway:
      enabled: true # Toggles the Gateway Actuator on or off
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - health
          - info
          - conditions
          - configprops
          - metrics
          - prometheus
  server:
    port: 8090 # actuators port
  tracing:
    enabled: false
spring:
  application:
    name: spring-cloud-gateway-for-kubernetes # application name

---
# Local response cache configuration (for activating LocalResponseCache filter)
spring:
  config:
    activate:
      on-profile: response-cache-local
  cloud:
    gateway:
      filter:
        local-response-cache:
          enabled: true
          time-to-live: 42s # Time-to-live before a cache entry is expired (300s, 5m, ..)
          size: 100MB     # Maximum size of cache (10MB, 900KB, 1GB,..)

