apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: atm-locator
spec:
  acceptedServiceBindings:
  - name: config
    types:
    - config
  build:
    path: .
